# This is the complex Travis configuration, which is intended for use
# on open source libraries which need compatibility across multiple GHC
# versions, must work with cabal-install, and should be
# cross-platform. For more information and other options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#

# Use new container infrastructure to enable caching
sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

  
# The different configurations we want to test. We have BUILD=cabal
# which uses cabal-install, and BUILD=stack which uses Stack. More
# documentation on each of those below.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.

matrix:
  include:
  - env: GHCVER=8.10.13 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.10.13
  allow_failures:
    - env: GHCVER=head STACK_YAML=stack-head.yaml


before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack config set system-ghc --global true
- export PATH=/opt/ghc/$GHCVER/bin:$PATH

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-8.10.13

script:
  - stack --no-terminal --skip-ghc-check test
  
