flags: {}
packages:
- .
- ../../TreeTagSets
- /home/frank/Workspace8/uniform/uniform-algebras
- /home/frank/Workspace8/uniform/uniform-strings
#- /home/frank/Workspace8/uniform/uniform-error
#- /home/frank/Workspace8/uniform/uniform-fileio
#- /home/frank/Workspace8/uniform/uniform-time
#- /home/frank/Workspace8/uniform/uniform-http
extra-deps:
- test-invariant-0.4.5.0
resolver: lts-10.8
